# Generated by Django 5.1.2 on 2024-11-12 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='doer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doer', to=settings.AUTH_USER_MODEL),
        ),
    ]
