name: 'Code Climate | Coverage'

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: 3.10.x
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Build project
        run: poetry build
             poetry run python manage.py migrate
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: poetry run coverage run manage.py test
          # coverageLocations: |
          #   ${{github.workspace}}/coverage.xml:coverage.py
