name: 'Code Climate | Coverage'

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: brokeyourbike/codeclimate-action@v0.1
      with:
        token: ${{ secrets.CC_TEST_REPORTER_ID }}
        files: .coverage
