name: 'Code Climate | Coverage'

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: 3.10.x
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install project
        run: poetry install --no-interaction --no-root
      - name: Static
        run: poetry run python manage.py collectstatic --no-input
      - name: Migrate
        run: poetry run python manage.py migrate
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
        with:
          coverageCommand: make coverage-xml
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:coverage.py
